### PR TITLE
kernel: defconfig: don't disable CONFIG_SECURITYFS

### PR DESCRIPTION
**Pull request by SergiiDmytruk**
It's necessary for reading TPM event log.

Probably was disabled accidentally in commit ba64a0fa0cf09f7b843692ae787383e95fc2f98c ("kernel: defconfig: Update and fix no video in UEFI boot").

### CODE REVIEW

**Comment by m-iwanicki** [comment]
@SergiiDmytruk After adding this config there is `/sys/kernel/security` but still no `/sys/kernel/security/tpm0/bios_binary_measurements`.

**Comment by SergiiDmytruk** [comment]
I see `/sys/kernel/security/tpm0/bios_binary_measurements` in Qemu with swtpm.  It might be missing if firmware and/or OS has trouble with TPM or TPM event log.

**Comment by m-iwanicki** [comment]
@SergiiDmytruk How do you start QEMU? I'm adding `-drive file=<trenchboot.wic path>,if=ide` to osfv `qemu-run.sh` script.
On Ubuntu there is `bios_binary_measurements` file so I don't think it's firmware fault.

**Comment by SergiiDmytruk** [comment]
I start it as described at https://github.com/Dasharo/open-source-firmware-validation/pull/360, so pretty much the same.

**Comment by SergiiDmytruk** [comment]
I get `/sys/kernel/security/tpm0/bios_binary_measurements` when I boot `meta-trenchboot` built with this change on APU3.  It's the same build I use with QEMU.

**Comment by m-iwanicki** [comment]
I'll check my build on APU3 to see if it's something with my QEMU, because I built and tested it multiple times.

**Comment by m-iwanicki** [comment]
Just checked on APU2C there still is no `/sys/kernel/security/tpm0` directory and also no `tpm_major_version` file.
Those files are available on `Debian 11`. Though on both systems no pcrs were available so maybe that's why there are some differences.
Also checked on `NovaCustom NV41PZ` and `bios_binary_measurements` exists. I wonder why there are such differences. Maybe different firmware.

**Review by m-iwanicki — APPROVED** [review]

**Pull request merged**
